version: '3.8'

services:
  chore-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chore-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this}
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5000}
    volumes:
      # Persist SQLite database
      - chore-db:/app/server/data
      # Optional: Mount local database for development
      # - ./server/chore_app.db:/app/server/chore_app.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  chore-db:
    driver: local
